name: build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual supplied image tag like 1.16.0'
        required: true
        type: string
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        if: ${{ inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ inputs.tags }}
          target: nginx
          tags: |
            ghcr.io/${{ github.repository }}/mapproxy:${{ inputs.tags }}
          platforms: linux/amd64,linux/arm64
      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          ignore-unfixed: true
          image-ref: 'ghcr.io/${{ github.repository }}/mapproxy:${{ inputs.tags }}'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
